apiVersion: v1
kind: Service
metadata:
  name: minecraft-access-service
  namespace: minecraft
spec:
  selector:
    app: minecraft-access
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
