apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: ttt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: ttt-server
          image: images.sourcegrade.org/jusito/docker-ttt:2024.1
          ports:
            - containerPort: 27015
              protocol: TCP
            - containerPort: 27015
              protocol: UDP
          env:
            - name: SERVER_PORT
              value: "27015"
            - name: INSTALL_CSS
              value: "true"
            - name: WORKSHOP_COLLECTION_ID
              value: "2061870598"
            - name: SERVER_NAME
              value: "My Server"
            - name: SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: server-password
            - name: SERVER_DEFAULT_MAP
              value: "ttt_waterworld"
