apiVersion: v1
kind: Service
metadata:
  name: server-1
  namespace: ttt
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/loadBalancerIPs: 10.0.10.11
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: server-1
  ports:
    - name: game-tcp
      protocol: TCP
      port: 27016
      targetPort: 27016
    - name: game-udp
      protocol: UDP
      port: 27016
      targetPort: 27016
