apiVersion: v1
kind: Service
metadata:
  name: server-0
  namespace: ttt
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/loadBalancerIPs: 10.0.10.10
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: server-0
  ports:
    - name: game-tcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: game-udp
      protocol: UDP
      port: 27015
      targetPort: 27015
