apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
  namespace: sourcegrade-ci
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Gi
  storageClassName: sourcegrade-ci-storage
