apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  namespace: sourcegrade-ci
spec:
  type: ClusterIP
  selector:
    app: teamcity-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8111
