apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
  alerting:
    alertmanagers:
      - namespace: prometheus
        name: alertmanager-main
        port: web
