apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-db-pvc
  namespace: staeding-matrix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: staeding-conduit-storage
