apiVersion: v1
kind: ConfigMap
metadata:
  name: well-known
  namespace: staeding-matrix
data:
  matrix.server: |
    {
      "m.server": "matrix.staeding.com:443"
    }
  matrix.client: |
    {
      "m.homeserver": {
        "base_url": "https://staeding.com"
      },
      "org.matrix.msc3575.proxy": {
        "url": "https://matrix.staeding.com"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: well-known
  namespace: staeding-matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: well-known
  template:
    metadata:
      labels:
        app: well-known
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: well-known
              mountPath: /usr/share/nginx/html/.well-known/matrix
      volumes:
        - name: well-known
          configMap:
            name: well-known
            items:
              - key: matrix.server
                path: server
              - key: matrix.client
                path: client
---
apiVersion: v1
kind: Service
metadata:
  name: well-known
  namespace: staeding-matrix
spec:
  clusterIP: None
  selector:
    app: well-known
  ports:
    - port: 80
      targetPort: 80
