apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
  labels:
    name: postgres-operator-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator-ui
  template:
    metadata:
      labels:
        name: postgres-operator-ui
    spec:
      serviceAccountName: postgres-operator-ui
      containers:
        - name: service
          image: registry.opensource.zalan.do/acid/postgres-operator-ui:v1.10.1
          ports:
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: APP_URL
              value: "http://localhost"
            - name: OPERATOR_API_URL
              value: "http://postgres-operator"
            - name: OPERATOR_CLUSTER_NAME_LABEL
              value: "postgres-operator-cluster"
            - name: RESOURCES_VISIBLE
              value: "False"
            - name: TARGET_NAMESPACE
              value: "*"
            - name: TEAMS
              value: |-
                [
                  "acid"
                ]
            - name: OPERATOR_UI_CONFIG
              value: |-
                {
                  "docs_link":"https://postgres-operator.readthedocs.io/en/latest/",
                  "dns_format_string": "{0}.{1}",
                  "databases_visible": true,
                  "master_load_balancer_visible": true,
                  "nat_gateways_visible": false,
                  "replica_load_balancer_visible": true,
                  "resources_visible": true,
                  "users_visible": true,
                  "cost_ebs": 0.0952,
                  "cost_iops": 0.006,
                  "cost_throughput": 0.0476,
                  "cost_core": 0.0575,
                  "cost_memory": 0.014375,
                  "free_iops": 3000,
                  "free_throughput": 125,
                  "limit_iops": 16000,
                  "limit_throughput": 1000,
                  "postgresql_versions": [
                    "15",
                    "14",
                    "13",
                    "12",
                    "11"
                  ]
                }
