apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teamcity-agent
  namespace: anvilpowered-ci
spec:
  serviceName: teamcity-agent
  replicas: 2  # Number of agents
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: teamcity-agent
          image: jetbrains/teamcity-agent:2023.11
          volumeMounts:
            - name: ramdisk
              mountPath: /opt/buildagent/work
            - name: config-volume
              mountPath: /opt/buildagent/conf
          env:
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_URL
              value: teamcity-server.anvilpowered-ci
      volumes:
        - name: ramdisk
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
  volumeClaimTemplates:
    - metadata:
        name: config-volume
      spec:
        accessModes: [ ReadWriteOnce ]
        storageClassName: anvilpowered-ci-storage
        resources:
          requests:
            storage: 4Gi
