apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: anvilpowered-ci-postgres
  namespace: anvilpowered-ci
spec:
  teamId: anvilpowered-ci
  volume:
    size: 32Gi
  numberOfInstances: 2
  users:
    teamcity:
      - login
  databases:
    teamcity: teamcity
  postgresql:
    version: "15"
