apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
  namespace: anvilpowered-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server:2023.05.4
          ports:
            - containerPort: 8111
          volumeMounts:
            - name: data-volume
              mountPath: /data/teamcity_server/datadir
            - name: log-volume
              mountPath: /opt/teamcity/logs
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: teamcity-server-data-pvc
        - name: log-volume
          persistentVolumeClaim:
            claimName: teamcity-server-log-pvc
