apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: anvilpowered-nexus
spec:
  clusterIP: None
  selector:
    app: nexus
  ports:
    - name: web
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: docker-images
      protocol: TCP
      port: 9000
      targetPort: 9000
