apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-e9e
  namespace: minecraft
  labels:
    app: minecraft-e9e
spec:
  serviceName: "minecraft-e9e-service-internal"
  replicas: 0
  selector:
    matchLabels:
      app: minecraft-e9e
  template:
    metadata:
      labels:
        app: minecraft-e9e
    spec:
      containers:
        - name: minecraft-e9e
          image: itzg/minecraft-server:2024.4.0-java21
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data-volume
              mountPath: /data
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CFG_PROXY_SECRET
              valueFrom:
                secretKeyRef:
                  name: minecraft-proxy-secret
                  key: secret-value
            - name: CFG_VELOCITY_ENABLED
              value: "true"
            - name: REPLACE_ENV_VARIABLE_PREFIX
              value: "CFG_"
            - name: TYPE
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge-secret
                  key: api-key
            - name: CF_SLUG
              value: "enigmatica9expert"
            - name: EULA
              value: "true"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: ONLINE_MODE
              value: "false"
            - name: MOTD
              value: "\u00A76Server-$(POD_NAME)"
            - name: "INIT_MEMORY"
              value: "24G"
            - name: "MAX_MEMORY"
              value: "32G"
            - name: JVM_OPTS
              value: "-Dfml.readTimeout=120"
            - name: MODS
              value: |
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/github-proxy/adde0109/Proxy-Compatible-Forge/releases/download/1.1.4/proxy-compatible-forge-1.19.2-1.1.4.jar
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "minecraft-storage"
        resources:
          requests:
            storage: 32Gi
