apiVersion: v1
kind: ConfigMap
metadata:
  name: nf-patches # neoforwarding patches
  namespace: minecraft
data:
  nf.json: |
    {
      "file": "/data/config/neoforwarding-server.toml",
      "ops": [
        {
          "$set": {
            "path": "$.forwardingSecret",
            "value": "${CFG_PROXY_SECRET}"
          }
        },
        {
          "$set": {
            "path": "$.enableForwarding",
            "value": true
          }
        }
      ]
    }
