apiVersion: v1
kind: ConfigMap
metadata:
  name: pv-patches # Paper-Velocity patches
  namespace: minecraft
data:
  pv.json: |
    {
      "file": "/data/config/paper-global.yml",
      "ops": [
        {
          "$set": {
            "path": "$.proxies.velocity.enabled",
            "value": "${CFG_VELOCITY_ENABLED}",
            "value-type": "bool"
          }
        },
        {
          "$set": {
            "path": "$.proxies.velocity.online-mode",
            "value": "true",
            "value-type": "bool"
          }
        },
        {
          "$set": {
            "path": "$.proxies.velocity.secret",
            "value": "${CFG_PROXY_SECRET}"
          }
        }
      ]
    }
