apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-lobby
  namespace: minecraft
  labels:
    app: minecraft-lobby
spec:
  selector:
    matchLabels:
      app: minecraft-lobby
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-lobby
    spec:
      containers:
        - name: minecraft-lobby
          image: itzg/minecraft-server:java17
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: minecraft-lobby-volume
              mountPath: /data
          env:
            - name: TYPE
              value: "PAPER"
            - name: EULA
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
      volumes:
        - name: minecraft-lobby-volume
          persistentVolumeClaim:
            claimName: minecraft-lobby-pvc
