apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-lobby
  namespace: minecraft
  labels:
    app: minecraft-lobby
spec:
  selector:
    matchLabels:
      app: minecraft-lobby
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-lobby
    spec:
      containers:
        - name: minecraft-lobby
          image: itzg/minecraft-server:java17
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
