apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-lobby
  namespace: minecraft
  labels:
    app: minecraft-lobby
spec:
  serviceName: "minecraft-lobby-service-internal"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-lobby
  template:
    metadata:
      labels:
        app: minecraft-lobby
    spec:
      containers:
        - name: minecraft-lobby
          image: itzg/minecraft-server:java17
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: paper-patches-volume
              mountPath: /config
            - name: data-volume
              mountPath: /data
          env:
            - name: CFG_PROXY_SECRET
              valueFrom:
                secretKeyRef:
                  name: minecraft-proxy-secret
                  key: secret-value
            - name: CFG_VELOCITY_ENABLED
              value: "true"
            - name: REPLACE_ENV_VARIABLE_PREFIX
              value: "CFG_"
            - name: PATCH_DEFINITIONS
              value: "/config/patch-set.json"
            - name: TYPE
              value: "PAPER"
            - name: EULA
              value: "true"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: "INIT_MEMORY"
              value: "2G"
            - name: "MAX_MEMORY"
              value: "8G"
            - name: PLUGINS
              value: |
                https://github.com/ViaVersion/ViaVersion/releases/download/4.8.1/ViaVersion-4.8.1.jar
                https://github.com/ViaVersion/ViaBackwards/releases/download/4.8.1/ViaBackwards-4.8.1.jar
                https://github.com/4drian3d/SignedVelocity/releases/download/1.2.1/SignedVelocity-Paper-1.2.1.jar
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
      volumes:
        - name: paper-patches-volume
          configMap:
            name: paper-patches
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "minecraft-storage"
        resources:
          requests:
            storage: 32Gi
