apiVersion: v1
kind: Service
metadata:
  name: minecraft-lobby-headless
  namespace: minecraft
spec:
  clusterIP: None
  selector:
    app: minecraft-lobby
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
