apiVersion: v1
kind: Service
metadata:
  name: minecraft-lobby-service-internal
  namespace: minecraft
spec:
  selector:
    app: minecraft-lobby
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: ClusterIP
