apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
  labels:
    app: teamcity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server:2023.05.1
          ports:
            - containerPort: 8111
          volumeMounts:
            - name: data-volume
              mountPath: /data/teamcity_server/datadir
            - name: logs-volume
              mountPath: /opt/teamcity/logs
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: teamcity-data-pvc
        - name: logs-volume
          persistentVolumeClaim:
            claimName: teamcity-logs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: teamcity-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: teamcity-storage
  resources:
    requests:
      storage: 2Gi
