apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-ups
  namespace: minecraft
  labels:
    app: minecraft-ups
spec:
  serviceName: "minecraft-ups-service-internal"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-ups
  template:
    metadata:
      labels:
        app: minecraft-ups
    spec:
      containers:
        - name: minecraft-ups
          image: itzg/minecraft-server:2023.11.0-java8
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data-volume
              mountPath: /data
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CFG_PROXY_SECRET
              valueFrom:
                secretKeyRef:
                  name: minecraft-proxy-secret
                  key: secret-value
            - name: CFG_VELOCITY_ENABLED
              value: "true"
            - name: REPLACE_ENV_VARIABLE_PREFIX
              value: "CFG_"
            - name: TYPE
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge-secret
                  key: api-key
            - name: CF_SLUG
              value: "ultimate-progression-sky"
            - name: CF_EXCLUDE_MODS
              value: "292899,459727" # Shulker Tooltip, Hidden Recipe Book
            - name: EULA
              value: "true"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: ONLINE_MODE
              value: "false"
            - name: MOTD
              value: "\u00A76Server-$(POD_NAME)"
            - name: "INIT_MEMORY"
              value: "24G"
            - name: "MAX_MEMORY"
              value: "32G"
            - name: JVM_OPTS
              value: "-Dfml.readTimeout=120"
            - name: MODS
              value: |
                https://github.com/adde0109/Proxy-Compatible-Forge/releases/download/1.1.4/proxy-compatible-forge-1.16.5-1.1.4.jar
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "minecraft-storage"
        resources:
          requests:
            storage: 32Gi
