apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: stackgres
  namespace: gitops-workshop
spec:
  instances: 1
  postgres:
    version: 'latest'
  pods:
    persistentVolume:
      size: '5Gi'
    scheduling:
      nodeSelector:
        type: worker
  sgInstanceProfile: 'size-s'
