apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: stackgres
  namespace: bench-postgres
spec:
  instances: 1
  postgres:
    version: 'latest'
  pods:
    persistentVolume:
      size: '5Gi'
  sgInstanceProfile: 'size-s'
