apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus
  namespace: cluster-repository
spec:
  serviceName: nexus
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - worker
      securityContext:
        fsGroup: 200  # Group ID for volume
      containers:
        - name: nexus
          image: sonatype/nexus3:3.68.1
          securityContext:
            runAsUser: 200  # User ID
          ports:
            - containerPort: 8081
            - containerPort: 9000
          volumeMounts:
            - name: data-volume
              mountPath: /nexus-data
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ ReadWriteMany ]
        storageClassName: cluster-repository-storage
        resources:
          requests:
            storage: 128Gi
