apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: cluster-repository
spec:
  clusterIP: None
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: web
