apiVersion: v1
kind: Service
metadata:
  name: ssh-reader
  namespace: minecraft
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/loadBalancerIPs: 10.0.10.2
spec:
  type: LoadBalancer
  selector:
    app: ssh-reader
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
