apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-access
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-access
  template:
    metadata:
      labels:
        app: minecraft-access
    spec:
      containers:
        - name: minecraft-access
          image: debian:bookworm
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          volumeMounts:
            - name: minecraft-proxy-volume
              mountPath: /servers/proxy
      volumes:
        - name: minecraft-proxy-volume
          persistentVolumeClaim:
            claimName: minecraft-proxy-pvc
