apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: minecraft-mysql
  namespace: minecraft
spec:
  secretName: minecraft-db
  tlsUseSelfSigned: true
  instances: 2
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteMany
    storageClassName: minecraft-db-storage
    resources:
      requests:
        storage: 128Gi
