apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: coder
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: coder-0.1.0
  name: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: coder
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: coder
        app.kubernetes.io/part-of: coder
        app.kubernetes.io/version: 0.1.0
        helm.sh/chart: coder-0.1.0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - coder
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - args:
            - server
          command:
            - /opt/coder
          env:
            - name: CODER_HTTP_ADDRESS
              value: 0.0.0.0:8080
            - name: CODER_PROMETHEUS_ADDRESS
              value: 0.0.0.0:2112
            - name: CODER_WILDCARD_ACCESS_URL
              value: "*.coder-ophase.ruben-deisenroth.de"
            - name: CODER_ACCESS_URL
              value: https://coder-ophase.ruben-deisenroth.de
            - name: CODER_OIDC_ISSUER_URL
              value: https://sso.ruben-deisenroth.de/application/o/coder/
            - name: CODER_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: coder-oidc-client-secret
                  key: id
            - name: CODER_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coder-oidc-client-secret
                  key: password
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-db-url
                  key: url
          image: ghcr.io/coder/coder:latest
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
          name: coder
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: null
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts: []
      restartPolicy: Always
      serviceAccountName: coder
      terminationGracePeriodSeconds: 60
      volumes: []
