apiVersion: v1
kind: Service
metadata:
  name: coder
  labels:
    helm.sh/chart: coder-0.1.0
    app.kubernetes.io/name: coder
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/part-of: coder
    app.kubernetes.io/version: "0.1.0"
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/loadBalancerIPs: 10.0.10.20
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: coder
    app.kubernetes.io/instance: release-name
  ports:
    - name: "http"
      port: 80
      targetPort: "http"
      protocol: TCP
