apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder-postgres
  namespace: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coder-postgres
  template:
    metadata:
      labels:
        app: coder-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.0
          env:
            - name: POSTGRES_DB
              value: coderdb
            - name: POSTGRES_USER
              value: coder
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coder-postgres-password
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: coder-postgres-pvc
