apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-postgres-pvc
  namespace: coder
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: coder-postgres-storage
