apiVersion: v1
kind: Service
metadata:
  name: coder-postgres-service-internal
  namespace: coder
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: coder-postgresql
