apiVersion: v1
kind: Service
metadata:
  name: rook-prometheus
  namespace: rook-ceph
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    prometheus: rook-prometheus
