apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon-service-internal
  namespace: minecraft
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/loadBalancerIPs: 10.0.10.80
spec:
  selector:
    app: minecraft-rcon
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4326
    - name: websocket
      protocol: TCP
      port: 4327
      targetPort: 4327
  type: LoadBalancer
