apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2023.10.0
          imagePullPolicy: Always
          args: [ "tunnel", "--no-autoupdate", "run", "--token=$(TOKEN)" ]
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-credentials
                  key: token
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
