apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - worker
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.6.0
          imagePullPolicy: Always
          args: [ "tunnel", "--no-autoupdate", "run", "--token=$(TOKEN)" ]
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-credentials
                  key: token
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
