- name: Install Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
    #    - name: Add GPG key for Kubernetes
    #      apt_key:
    #        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    #        state: present
    #    - name: Add Kubernetes repository
    #      apt_repository:
    #        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    #        filename: kubernetes.list
    #        state: present
    - name: Add Kubernetes repository
      deb822_repository:
        name: kubernetes
        types: deb
        uris: https://apt.kubernetes.io/
        suites: kubernetes-xenial
        components: main
        signed_by: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Kubernetes
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
    - name: Hold Kubernetes packages at current version
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
