- name: Install Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
    - name: Add Kubernetes repository
      deb822_repository:
        name: kubernetes
        types: deb
        uris: https://apt.kubernetes.io/
        suites: kubernetes-xenial
        components: main
        signed_by: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: Add Helm repository
      deb822_repository:
        name: helm
        types: deb
        uris: https://baltocdn.com/helm/stable/debian/
        suites: all
        components: main
        signed_by: https://baltocdn.com/helm/signing.asc
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Kubernetes
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
    - name: Hold Kubernetes packages at current version
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
    - name: Install Helm
      apt:
        name: helm
        state: present
    - name: Create kube user
      user:
        name: kube
        state: present
        shell: /bin/bash
        createhome: yes
        group: kube
        groups: ""
