apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-proxy
  namespace: minecraft
  labels:
    app: minecraft-proxy
spec:
  selector:
    matchLabels:
      app: minecraft-proxy
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - worker
      containers:
        - name: minecraft-proxy
          image: itzg/bungeecord:2024.2.0
          ports:
            - containerPort: 25577
          volumeMounts:
            - name: minecraft-proxy-volume
              mountPath: /server/logs
              subPath: logs
            - name: minecraft-proxy-volume
              mountPath: /server/plugins
              subPath: plugins
            - name: velocity-config-volume
              mountPath: /config/velocity.toml
              subPath: velocity.toml
            - name: proxy-secret-volume
              mountPath: /config/forwarding.secret
              subPath: secret-value
            - name: lp-patches-volume
              mountPath: /config/patches/lp.json
              subPath: lp.json
          env:
            - name: TYPE
              value: "VELOCITY"
            - name: VELOCITY_VERSION
              value: "3.3.0-SNAPSHOT"
            - name: VELOCITY_BUILD_ID
              value: "370"
            - name: PLUGINS
              value: |
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/github-proxy/adde0109/Ambassador/releases/download/v1.5.0-rc1-beta/Ambassador-Velocity-1.5.0-rc1-all.jar
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/github-proxy/4drian3d/SignedVelocity/releases/download/1.2.3/SignedVelocity-Proxy-1.2.3.jar
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/mc-bin/anvilpowered/catalyst/catalyst-0.4.0-RC35.jar
                https://download.luckperms.net/1532/velocity/LuckPerms-Velocity-5.4.119.jar
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
            - name: REPLACE_ENV_VARIABLE_PREFIX
              value: ""
            - name: PATCH_DEFINITIONS
              value: "/config/patches"
            - name: CFG_LP_CONFIG
              value: "/server/plugins/luckperms/config.yml"
            - name: CFG_LP_ADDRESS
              value: "minecraft-postgres.minecraft"
            - name: CFG_LP_DATABASE
              value: "luckperms"
            - name: CFG_LP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: luckperms.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: CFG_LP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: luckperms.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: CATALYST_DB_URL
              value: "jdbc:postgresql://minecraft-postgres.minecraft:5432/catalyst"
            - name: CATALYST_DB_USER
              valueFrom:
                secretKeyRef:
                  name: catalyst.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: CATALYST_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalyst.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: CATALYST_CHAT_DISCORD_ENABLED
              value: "true"
            - name: CATALYST_CHAT_DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: catalyst-tokens
                  key: discord-bot-token
            - name: CATALYST_CHAT_CHANNELS
              value: |
                {
                  "global": {
                    "id": "global",
                    "name": "<green>[Global]",
                    "nameFormat": "<gold>[%backend.name%]</gold>%prefix% %displayname%",
                    "contentFormat": "%content%",
                    "messageFormat": "%channel.name% %name%: %content%",
                    "commandAliases": [
                       "g",
                       "global"
                    ],
                    "alwaysVisible": true,
                    "availableByDefault": true,
                    "discordChannelId": "1173726070525132911"
                  },
                  "staff": {
                    "id": "staff",
                    "name": "<aqua>[Staff]",
                    "nameFormat": "<gold>[%backend.name%]</gold>%prefix% %displayname%",
                    "contentFormat": "%content%",
                    "messageFormat": "<aqua>%channel.name% %name%: %content%",
                    "commandAliases": [
                       "sc",
                       "staffchat"
                    ],
                    "alwaysVisible": true,
                    "availableByDefault": false,
                    "discordChannelId": "1197313444395880558"
                  }
                }
      volumes:
        - name: minecraft-proxy-volume
          persistentVolumeClaim:
            claimName: minecraft-proxy-pvc
        - name: velocity-config-volume
          configMap:
            name: velocity-config
        - name: proxy-secret-volume
          secret:
            secretName: minecraft-proxy-secret
        - name: lp-patches-volume
          configMap:
            name: lp-patches
