apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-proxy
  namespace: minecraft
  labels:
    app: minecraft-proxy
spec:
  selector:
    matchLabels:
      app: minecraft-proxy
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      initContainers:
        - name: init-velocity
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /server/velocity.toml ]; then
                wget -O /server/velocity.toml https://raw.githubusercontent.com/PaperMC/Velocity/dev/3.0.0/proxy/src/main/resources/default-velocity.toml
              fi
              echo $CFG_PROXY_SECRET > /server/forwarding.secret
          env:
            - name: CFG_PROXY_SECRET
              valueFrom:
                secretKeyRef:
                  name: minecraft-proxy-secret
                  key: secret-value
          volumeMounts:
            - name: minecraft-proxy-volume
              mountPath: /server
      containers:
        - name: minecraft-proxy
          image: itzg/bungeecord:latest
          ports:
            - containerPort: 25577
          volumeMounts:
            - name: minecraft-proxy-volume
              mountPath: /server/logs
              subPath: logs
            - name: minecraft-proxy-volume
              mountPath: /server/plugins
              subPath: plugins
            - name: minecraft-proxy-volume
              mountPath: /server/velocity.toml
              subPath: velocity.toml
            - name: minecraft-proxy-volume
              mountPath: /server/forwarding.secret
              subPath: forwarding.secret
            - name: lp-patches-volume
              mountPath: /config
          env:
            - name: TYPE
              value: "VELOCITY"
            - name: VELOCITY_VERSION
              value: "3.2.0-SNAPSHOT"
            - name: VELOCITY_BUILD_ID
              value: "294"
            - name: PLUGINS
              value: |
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/github-proxy/adde0109/Ambassador/releases/download/v1.4.3-beta/Ambassador-Velocity-1.4.3-beta-all.jar
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/github-proxy/4drian3d/SignedVelocity/releases/download/1.2.1/SignedVelocity-Proxy-1.2.1.jar
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/mc-bin/anvilpowered/catalyst/catalyst-0.4.0-SNAPSHOT-all.jar
                https://download.luckperms.net/1521/velocity/LuckPerms-Velocity-5.4.108.jar
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
            - name: REPLACE_ENV_VARIABLE_PREFIX
              value: ""
            - name: PATCH_DEFINITIONS
              value: "/config/lp-patch-set.json"
            - name: CFG_LP_CONFIG
              value: "/server/plugins/luckperms/config.yml"
            - name: CFG_LP_ADDRESS
              value: "minecraft-postgres.minecraft"
            - name: CFG_LP_DATABASE
              value: "luckperms"
            - name: CFG_LP_USERNAME
              valueFrom:
                secretKeyRef:
                name: luckperms.minecraft-postgres.credentials.postgresql.acid.zalan.do
                key: username
            - name: CFG_LP_PASSWORD
              valueFrom:
                secretKeyRef:
                name: luckperms.minecraft-postgres.credentials.postgresql.acid.zalan.do
                key: password
            - name: CATALYST_DB_URL
              value: "jdbc:postgresql://minecraft-postgres.minecraft:5432/catalyst"
            - name: CATALYST_DB_USER
              valueFrom:
                secretKeyRef:
                  name: catalyst.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: CATALYST_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalyst.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: CATALYST_DISCORD_ENABLED
              value: "true"
            - name: CATALYST_DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                name: catalyst-tokens
                key: discord-bot-token
      volumes:
        - name: minecraft-proxy-volume
          persistentVolumeClaim:
            claimName: minecraft-proxy-pvc
        - name: secret-volume
          secret:
            secretName: minecraft-proxy-secret
        - name: lp-patches-volume
          configMap:
            name: lp-patches
