apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-proxy
  namespace: minecraft
  labels:
    app: minecraft-proxy
spec:
  selector:
    matchLabels:
      app: minecraft-proxy
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      initContainers:
        - name: init-velocity
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /server/velocity.toml ]; then
                wget -O /server/velocity.toml https://raw.githubusercontent.com/PaperMC/Velocity/dev/3.0.0/proxy/src/main/resources/default-velocity.toml
              fi
              echo $CFG_PROXY_SECRET > /server/forwarding.secret
          env:
            - name: CFG_PROXY_SECRET
              valueFrom:
                secretKeyRef:
                  name: minecraft-proxy-secret
                  key: secret-value
          volumeMounts:
            - name: minecraft-proxy-volume
              mountPath: /server
      containers:
        - name: minecraft-proxy
          image: itzg/bungeecord:java17
          ports:
            - containerPort: 25577
          volumeMounts:
            - name: minecraft-proxy-volume
              mountPath: /server/logs
              subPath: logs
            - name: minecraft-proxy-volume
              mountPath: /server/plugins
              subPath: plugins
            - name: minecraft-proxy-volume
              mountPath: /server/velocity.toml
              subPath: velocity.toml
            - name: minecraft-proxy-volume
              mountPath: /server/forwarding.secret
              subPath: forwarding.secret
          env:
            - name: TYPE
              value: "VELOCITY"
            - name: VELOCITY_VERSION
              value: "3.2.0-SNAPSHOT"
            - name: VELOCITY_BUILD_ID
              value: "276"
            - name: PLUGINS
              value: |
                https://github.com/adde0109/Ambassador/releases/download/v1.4.3-beta/Ambassador-Velocity-1.4.3-beta-all.jar
                https://github.com/WiIIiam278/HuskChat/releases/download/2.7.1/HuskChat-2.7.1.jar
                https://github.com/4drian3d/SignedVelocity/releases/download/1.2.1/SignedVelocity-Proxy-1.2.1.jar
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
      volumes:
        - name: minecraft-proxy-volume
          persistentVolumeClaim:
            claimName: minecraft-proxy-pvc
        - name: secret-volume
          secret:
            secretName: minecraft-proxy-secret
