apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-proxy
  namespace: minecraft
  labels:
    app: minecraft-proxy
spec:
  selector:
    matchLabels:
      app: minecraft-proxy
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      containers:
        - name: minecraft-proxy
          image: dockcenter/velocity:3.2.0-SNAPSHOT-260
          ports:
            - containerPort: 25577
          volumeMounts:
            - name: minecraft-proxy-volume
              mountPath: /data
            - name: secret-volume
              mountPath: /data/forwarding.secret
              subPath: secret-value
              readOnly: true
      volumes:
        - name: minecraft-proxy-volume
          persistentVolumeClaim:
            claimName: minecraft-proxy-pvc
        - name: secret-volume
          secret:
            secretName: minecraft-proxy-secret
