apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-proxy-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: minecraft-proxy-storage
