apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-vanilla
  namespace: minecraft
  labels:
    app: minecraft-vanilla
spec:
  serviceName: "minecraft-vanilla-service-internal"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-vanilla
  template:
    metadata:
      labels:
        app: minecraft-vanilla
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - worker
      containers:
        - name: minecraft-vanilla
          image: itzg/minecraft-server:2024.12.1
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: pv-patches-volume
              mountPath: /config/config/patches/pv.json
              subPath: pv.json
            - name: lp-patches-volume
              mountPath: /config/config/patches/lp.json
              subPath: lp.json
            - name: vanilla-bukkit-yml-volume
              mountPath: /config/bukkit.yml
              subPath: bukkit.yml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CFG_PROXY_SECRET
              valueFrom:
                secretKeyRef:
                  name: minecraft-proxy-secret
                  key: secret-value
            - name: CFG_VELOCITY_ENABLED
              value: "true"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.21.4"
            - name: PAPER_CHANNEL
              value: "experimental"
            - name: PAPER_BUILD
              value: "59"
            - name: EULA
              value: "true"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: ONLINE_MODE
              value: "false"
            - name: MOTD
              value: "\u00A76Server-$(POD_NAME)"
            - name: "INIT_MEMORY"
              value: "2G"
            - name: "MAX_MEMORY"
              value: "8G"
            - name: "VIEW_DISTANCE"
              value: "32"
            - name: "SIMULATION_DISTANCE"
              value: "16"
            - name: PLUGINS
              value: |
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/luckperms-proxy/1568/bukkit/loader/LuckPerms-Bukkit-5.4.151.jar
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/github-proxy/4drian3d/SignedVelocity/releases/download/1.3.0/SignedVelocity-Paper-1.3.0.jar
                http://nexus-0.nexus.minecraft.svc.cluster.local:8081/repository/mc-bin/griefdefender/griefdefender-bukkit-3.0.3.jar
                https://cdn.modrinth.com/data/hXiIvTyT/versions/puUfqBpY/EssentialsX-2.20.1.jar
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-web-secret
                  key: RCON_PASSWORD
            - name: REPLACE_ENV_VARIABLE_PREFIX
              value: ""
            - name: "COPY_CONFIG_DEST"
              value: "/data"
            - name: PATCH_DEFINITIONS
              value: "/config/patches"
            - name: "ENABLE_WHITELIST"
              value: "false"
            - name: CFG_LP_CONFIG
              value: "/data/plugins/LuckPerms/config.yml"
            - name: CFG_LP_ADDRESS
              value: "minecraft-postgres.minecraft"
            - name: CFG_LP_DATABASE
              value: "luckperms"
            - name: CFG_LP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: luckperms.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: CFG_LP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: luckperms.minecraft-postgres.credentials.postgresql.acid.zalan.do
                  key: password
      volumes:
        - name: pv-patches-volume
          configMap:
            name: pv-patches
        - name: lp-patches-volume
          configMap:
            name: lp-patches
        - name: vanilla-bukkit-yml-volume
          configMap:
            name: vanilla-bukkit-yml
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "minecraft-storage"
        resources:
          requests:
            storage: 32Gi
