apiVersion: v1
kind: Service
metadata:
  name: minecraft-vanilla-headless
  namespace: minecraft
spec:
  clusterIP: None
  selector:
    app: minecraft-vanilla
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
