apiVersion: v1
kind: Service
metadata:
  name: minecraft-vanilla-service-internal
  namespace: minecraft
spec:
  selector:
    app: minecraft-vanilla
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: ClusterIP
