apiVersion: v1
kind: Service
metadata:
  name: nvr-service
  namespace: nvr
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/loadBalancerIPs: 10.0.10.5
spec:
  selector:
    app: nvr-frigate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
